[greeter]
background=/usr/share/backgrounds/kali-livehunter/livehunter_wallpaper.png
logo=/usr/share/pixmaps/kali-livehunter-logo.png
theme-name=Kali-Dark
icon-theme-name=Flat-Remix-Blue-Dark
font-name=Noto Sans 10
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
